# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
registries:
  dockerhub:
    type: docker-registry
    url: registry.hub.docker.com
    username: ${{secrets.DOCKER_USER}}
    password: ${{secrets.DOCKER_PASS}}
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/.github"
    schedule:
      interval: "weekly"
    assignees:
      - "derskythe"
      
  - package-ecosystem: "composer" # See documentation for possible values
    directory: "/.templates" # Location of package manifests
    schedule:
      interval: "weekly"
    assignees:
      - "derskythe"

  - package-ecosystem: "pip"
    directory: "/scripts"
    schedule:
      interval: "weekly"
    assignees:
      - "derskythe"

  - package-ecosystem: "pipenv"
    directory: "/scripts"
    schedule:
      interval: "weekly"
    assignees:
      - "derskythe"

  - package-ecosystem: "docker"
    directory: "./templates"
    schedule:
      interval: "weekly"
    assignees:
      - "derskythe"

  - package-ecosystem: "beta-ecosystem"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "derskythe"
